name: Vercel deployment preview link generator

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'website/docs/docs/**'
      - 'website/docs/best-practices/**'
      - 'website/docs/guides/**'
      - 'website/docs/faqs/**'
      - 'website/docs/reference/**'

permissions:
  contents: read
  pull-requests: write
  checks: read  # Added permission to read checks

jobs:
  comment-deployment-link:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install necessary tools
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl

      - name: Generate Vercel deployment URL
        id: vercel_url
        run: |
          # Get the branch name
          BRANCH_NAME="${{ github.head_ref }}"

          # Convert to lowercase
          BRANCH_NAME_LOWER=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]')

          # Replace non-alphanumeric characters with hyphens
          BRANCH_NAME_SANITIZED=$(echo "$BRANCH_NAME_LOWER" | sed 's/[^a-z0-9]/-/g')

          # Construct the deployment URL
          DEPLOYMENT_URL="https://docs-getdbt-com-git-${BRANCH_NAME_SANITIZED}-dbt-labs.vercel.app"

          echo "deployment_url=$DEPLOYMENT_URL" >> $GITHUB_OUTPUT

      - name: Wait for Vercel deployment check to complete
        id: wait_for_vercel
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Set variables
          COMMIT_SHA="${{ github.event.pull_request.head.sha }}"
          REPO="${{ github.repository }}"

          echo "Waiting for Vercel deployment check to complete..."

          MAX_ATTEMPTS=60  # Adjust as needed
          SLEEP_TIME=10    # Check every 10 seconds
          ATTEMPTS=0

          while [ $ATTEMPTS -lt $MAX_ATTEMPTS ]; do
            # Get the check runs for the commit
            CHECK_RUNS=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
              "https://api.github.com/repos/$REPO/commits/$COMMIT_SHA/check-runs")

            # Filter for the Vercel check run
            VERCEL_CHECK=$(echo "$CHECK_RUNS" | jq -r '.check_runs[] | select(.name == "Vercel")')

            if [ -n "$VERCEL_CHECK" ]; then
              STATUS=$(echo "$VERCEL_CHECK" | jq -r '.status')
              CONCLUSION=$(echo "$VERCEL_CHECK" | jq -r '.conclusion')

              echo "Vercel check status: $STATUS"

              if [ "$STATUS" == "completed" ]; then
                if [ "$CONCLUSION" == "success" ]; then
                  echo "Vercel deployment check completed successfully."
                  break
                else
                  echo "Vercel deployment check failed."
                  exit 1
                fi
              fi
            else
              echo "Vercel check not found. Waiting..."
            fi

            sleep $SLEEP_TIME
            ATTEMPTS=$((ATTEMPTS + 1))
          done

          if [ $ATTEMPTS -eq $MAX_ATTEMPTS ]; then
            echo "Vercel deployment check did not complete within expected time."
            exit 1
          fi

      - name: Get changed files
        id: files
        run: |
          # Get the list of changed files in the specified directories
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | grep -E '^website/docs/(docs|best-practices|guides|faqs|reference)/.*\.md$' || true)
          echo "Changed files:"
          echo "$CHANGED_FILES"

          # Check if any files were changed
          if [ -z "$CHANGED_FILES" ]; then
            echo "No documentation files were changed."
            echo "changed_files=" >> $GITHUB_OUTPUT
          else
            # Convert line-separated files to space-separated for easier handling
            CHANGED_FILES="$(echo "$CHANGED_FILES" | tr '\n' ' ')"
            echo "changed_files=$CHANGED_FILES" >> $GITHUB_OUTPUT
          fi

      - name: Generate file preview links
        id: links
        run: |
          DEPLOYMENT_URL="${{ steps.vercel_url.outputs.deployment_url }}"
          CHANGED_FILES="${{ steps.files.outputs.changed_files }}"

          if [ -z "$CHANGED_FILES" ]; then
            echo "No changed files found in the specified directories."
            LINKS="- No documentation files were changed."
          else
            LINKS=""
            # Convert CHANGED_FILES back to newline-separated for processing
            CHANGED_FILES=$(echo "$CHANGED_FILES" | tr ' ' '\n')
            for FILE in $CHANGED_FILES; do
              # Remove 'website/docs/' prefix
              FILE_PATH="${FILE#website/docs/}"
              # Remove the .md extension
              FILE_PATH="${FILE_PATH%.md}"

              # Construct the full URL
              FULL_URL="$DEPLOYMENT_URL/$FILE_PATH"
              LINKS="$LINKS\n- $FULL_URL"
            done
          fi

          # Properly set the multi-line output
          echo "links<<EOF" >> $GITHUB_OUTPUT
          echo -e "$LINKS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post comment with deployment link
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { github, context } = require('@actions/github');
            const issue_number = context.payload.pull_request.number;
            const links = `\n${{ steps.links.outputs.links }}`;
            const body = `<!-- vercel-preview-comment -->\n🚀 Deployment available! Here are the direct links to the updated files:${links}`;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number,
              body: body
            });
