name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          separator: ' '
          files: |
            **/*.md
            **/*.txt
            **/*.rst

      - name: Install Vale
        env:
          VALE_VERSION: v2.27.0  # Use a stable version
        run: |
          curl -fsSL https://install.goreleaser.com/github.com/errata-ai/vale.sh | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          vale sync

      - name: Set VALE_FILES environment variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: echo "VALE_FILES=${{ steps.changed-files.outputs.all_changed_and_modified_files }}" >> $GITHUB_ENV
  
      - name: Run Vale
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: errata-ai/vale-action@reviewdog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
