name: Lint and suggest

on:
  pull_request:
    paths:
      - '**/*.md'

permissions:
  contents: read
  pull-requests: write

jobs:
  vale: # Vale linting job
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Vale
      uses: errata-ai/vale-action@v2
      with:
        reporter: github-pr-check

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Run Vale on changed files
      run: |
        changed_files=$(git diff --name-only --diff-filter=ACMRT HEAD^ HEAD -- '*.md')
        if [ -z "$changed_files" ]; then
          echo "No changed markdown files."
          exit 0
        fi

        for file in $changed_files; do
          echo "Running Vale on $file"
          vale --output=JSON $file > "vale_output_${file//\//_}.json"
          vale --output=edit $file > "vale_output_${file//\//_}_edit.md"
        done
        echo "Vale outputs:"
        ls -l

