name: Vale lint checker

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Install Vale
        run: |
          curl -L https://github.com/errata-ai/vale/releases/download/v2.17.0/vale_2.17.0_Linux_64-bit.tar.gz -o vale.tar.gz
          tar -xvzf vale.tar.gz
          sudo mv vale /usr/local/bin/

      - name: Set VALE_CONFIG_PATH
        run: echo "VALE_CONFIG_PATH=$(pwd)/.vale.ini" >> $GITHUB_ENV

      - name: Set up Vale with Reviewdog
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["website/docs/docs", "website/docs/reference","website/docs/guides"]'
          token: ${{ secrets.GITHUB_TOKEN }}
          version: 2.17.0
          reporter: github-pr-check

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- '*.md' '*.txt' '*.rst' | tr '\n' ' ')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Debug CHANGED_FILES
        run: |
          echo "Changed files: ${{ env.CHANGED_FILES }}"
