name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/docs/**/*'
      - 'website/blog/**/*'
      - 'website/**/*'

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Vale
        run: pip install vale

      - name: Find changed lines and files
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1
        with:
          file_filter: '.md'
          delimiter: ','  # Use comma as the delimiter

      - name: Run Vale
        if: ${{ steps.changed_lines.outputs.changed_files != '' }}
        uses: errata-ai/vale-action@v2  # Use a valid version tag
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          files: ${{ steps.changed_lines.outputs.changed_files }}
          separator: ','
