name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/docs/**/*'
      - 'website/blog/**/*'
      - 'website/**/*'

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Vale
        run: pip install vale

      - name: Find changed lines and files
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1
        with:
          file_filter: '.md'
          delimiter: ','  # Use comma as the delimiter

      - name: Adjust file paths
        if: ${{ steps.changed_lines.outputs.changed_files != '' }}
        id: adjust_paths
        run: |
          echo "Adjusting file paths"
          echo "${{ steps.changed_lines.outputs.changed_files }}" > changed_files_raw.txt
          # Remove 'website/' prefix from each file path
          adjusted_files=$(cat changed_files_raw.txt | sed 's|website/||g')
          echo "Adjusted files:"
          echo "$adjusted_files"
          echo "ADJUSTED_FILES=$adjusted_files" >> $GITHUB_ENV

      - name: Run Vale
        if: ${{ env.ADJUSTED_FILES != '' }}
        uses: errata-ai/vale-action@reviewdog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          files: ${{ env.ADJUSTED_FILES }}
          separator: ','
          version: '3.7.1'
