name: Vale lint checker

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set environment variables
        run: |
          echo "HOME=/home/runner" >> $GITHUB_ENV
          echo "VALE_CONFIG_PATH=$(pwd)/.vale.ini" >> $GITHUB_ENV

      - name: Run Vale with Reviewdog
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '**/*.md'
          token: ${{ secrets.GITHUB_TOKEN }}
          version: '2.17.0'
          reporter: github-pr-check
          level: error
          filter_mode: diff_context
        env:
          HOME: /home/runner
          VALE_CONFIG_PATH: $(pwd)/.vale.ini
