name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/docs/**/*'
      - 'website/blog/**/*'
      - 'website/**/*'

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Vale
        run: pip install vale

      - name: Find changed lines and files
        id: changed_lines
        uses: hestonhoffman/changed-lines@v1
        with:
          file_filter: '.md'
          # Ensure the output is newline-separated
          delimiter: ','

      - name: Prepare files for Vale
        if: ${{ steps.changed_lines.outputs.changed_files != '' }}
        run: |
          echo "Formatting changed files for Vale"
          # Remove any empty lines
          echo "${{ steps.changed_lines.outputs.changed_files }}" | awk 'NF' > changed_files.txt
          # Create a comma-separated list
          files_list=$(paste -sd ',' changed_files.txt)
          echo "Formatted files as comma-separated list:"
          echo "$files_list"
          echo "VALE_FILES=$files_list" >> $GITHUB_ENV

      - name: Run Vale
        if: ${{ steps.changed_lines.outputs.changed_files != '' }}
        uses: errata-ai/vale-action@reviewdog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          files: ${{ env.VALE_FILES }}
          separator: ','
