name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/docs/**/*'
      - 'website/blog/**/*'
      - 'website/**/*'

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List repository contents
        run: |
          pwd
          ls -R

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Vale
        run: pip install vale==3.0.0  # Install a stable version of Vale

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            website/**/*.md
          separator: ' '

      - name: Debugging - Print changed files
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "Changed files:"
          echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}"

      - name: Confirm files exist
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: |
          echo "Checking if files exist..."
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            if [ -f "$file" ]; then
              echo "Found: $file"
            else
              echo "File not found: $file"
              exit 1
            fi
          done

      - name: Run Vale
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: errata-ai/vale-action@reviewdog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          files: ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          separator: ' '
          version: '3.0.0'
