name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          separator: ' '
          files: |
            **/*.md
            **/*.txt
            **/*.rst

      - name: Set VALE_FILES environment variable
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        run: echo "VALE_FILES=${{ steps.changed-files.outputs.all_changed_and_modified_files }}" >> $GITHUB_ENV

      - name: Run Vale
        if: ${{ steps.changed-files.outputs.any_changed == 'true' }}
        uses: errata-ai/vale-action@reviewdog
