name: Vale linting check

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest
    

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vale
        uses: errata-ai/vale-action@reviewdog

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep -E '^website/docs/(docs|reference|guides)/.*\.(md|txt|rst)$' | tr '\n' ' ')
          echo "files=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Run Vale
        run: |
          for file in ${{ env.files }}; do
            vale "$file"
          done
