name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'website/docs/**/*'
      - 'website/blog/**/*'
      - 'website/**/*'

jobs:
  vale:
    name: Vale Linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Vale
        run: pip install vale

      - name: Find changed lines adn files
        id: changed-files
        uses: hestonhoffman/changed-lines@v1
        with: 
          file_filter: '.md'

      - name: Set VALE_FILES environment variable
        if: ${{ steps.changed_lines.outputs.changed_files != '' }}
        run: echo "VALE_FILES=${{ steps.changed_lines.outputs.changed_files }}" >> $GITHUB_ENV

      - name: Run Vale
        if: ${{ steps.changed_lines.outputs.changed_files == 'true' }}
        uses: errata-ai/vale-action@reviewdog
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
