name: reviewdog

on: 
  pull_request:

jobs:
  vale:
    name: runner / vale
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Reviewdog with Vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["website/docs/docs", "website/docs/reference", "website/docs/guides"]'
          reporter: github-pr-check
          token: ${{ secrets.VALE_GITHUB_TOKEN }}

      - name: Get changed files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- '*.md' '*.txt' '*.rst' | tr '\n' ' ')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Debug CHANGED_FILES
        run: |
          echo "Changed files: ${{ env.CHANGED_FILES }}"

      - name: Run Vale with Reviewdog on Changed Files
        if: env.CHANGED_FILES != ''
        run: |
          for file in ${{ env.CHANGED_FILES }}; do
            vale --output=JSON "$file" | reviewdog -f=vale -name="vale" -reporter=github-pr-check -level=warning -filter-mode=added -fail-on-error=true -tee
          done
