name: Vale Lint Checker

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set VALE_CONFIG_PATH
        run: echo "VALE_CONFIG_PATH=$(pwd)/.vale.ini" >> $GITHUB_ENV

      - name: Get Changed Files
        id: changed-files
        run: |
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- '*.md' '*.txt' '*.rst')
          echo "changed_files=${CHANGED_FILES}" >> $GITHUB_OUTPUT
          echo "Changed files:"
          echo "${CHANGED_FILES}"

      - name: Run Vale with Reviewdog
        if: steps.changed-files.outputs.changed_files != ''
        uses: reviewdog/action-vale@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          args: '${{ steps.changed-files.outputs.changed_files }}'
        env:
          VALE_CONFIG_PATH: ${{ env.VALE_CONFIG_PATH }}
