name: Vale linting check

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Vale
        uses: errata-ai/vale-action@v2
        with:
          files: website/docs/docs

      - name: Get changed files
        id: changed-files
        run: |
          echo "::set-output name=files::$(git diff --name-only ${{ github.base_ref }} ${{ github.head_ref }} | grep '\.md\|\.txt\|\.rst' | tr '\n' ' ')"
  
      - name: Run Vale
        run: |
          for file in ${{ steps.changed-files.outputs.files }}; do
            vale "$file"
          done
