name: Vale Linting

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  vale:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            **/*.md
            **/*.txt
            **/*.rst
          separator: '\n'

      - name: Run Vale
        uses: errata-ai/vale-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          wrapper_script: |
            echo "${{ steps.changed-files.outputs.all_changed_and_modified_files }}" > file_list.txt
            cat file_list.txt | xargs vale
