name: Vale lint checker

on:
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Vale
        uses: actions/cache@v3
        with:
          path: ~/.vale
          key: ${{ runner.os }}-vale-${{ hashFiles('**/.vale.ini') }}
          restore-keys: |
            ${{ runner.os }}-vale-

      - name: Set up vale
        uses: errata-ai/vale-action@reviewdog
        with:
          files: '["docs/docs", "docs/reference", "docs/guides", "docs/best-practices"]'
          token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check

      - name: Check if Vale is installed
        run: |
          if ! command -v vale &> /dev/null; then
            echo "Vale is not installed correctly."
            exit 1
          fi

      - name: Install Reviewdog
        uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest

      - name: Get changed files
        id: changed-files
        run: |
          git fetch origin ${{ github.base_ref }} ${{ github.head_ref }}
          CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }} origin/${{ github.head_ref }} -- '*.md' '*.txt' '*.rst' | tr '\n' ' ')
          echo "CHANGED_FILES=$CHANGED_FILES" >> $GITHUB_ENV

      - name: Debug CHANGED_FILES
        run: |
          echo "Changed files: ${{ env.CHANGED_FILES }}"

      - name: Run vale with reviewdog
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -z "${{ env.CHANGED_FILES }}" ]; then
            echo "No changed files to lint."
          else
            for file in ${{ env.CHANGED_FILES }}; do
              vale --output=checkstyle "$file" | reviewdog -f=checkstyle -name="vale" -reporter=github-pr-check -level=warning -filter-mode=added -fail-on-error=true -tee
            done
          fi
